version: '3'
services:

  php:
    image: jguyomard/laravel-php:7.2
    volumes:
      - ./:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      - "DB_HOST=localhost"
      - "DB_DATABASE=vb_passion"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"

  nginx:
    image: jguyomard/laravel-nginx:1.13
    ports:
      - 8080:80

  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=vb_passion"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
    ports:
        - "3306:3306"

volumes:
  mysqldata:

